[project]
site_name = "xlpath"
site_description = "Query the XML within Excel XLSX files using XPath."
nav = [
  { "Get started" = "index.md" },
  { "Usage" = "usage.md" },
  { "Output format" = "output.md" },
  { "Examples" = "examples.md" },
  { "XML namespaces" = "namespaces.md" },
  { "See also" = "see-also.md" },
]
repo_url = "https://github.com/flother/xlpath"

[project.theme]
language = "en"
favicon = "favicon.svg"

features = [
    "content.action.edit",
    "content.action.view",
    "content.code.copy",
    "navigation.footer",
    "navigation.indexes",
    "navigation.path",
    "navigation.sections",
]

[project.theme.icon]
logo = "lucide/file-spreadsheet"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.extra]
generator = false

# https://zensical.org/docs/setup/extensions/
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
